development:
  adapter: postgresql
  encoding: utf8
  database: project_development_CourseCatalog
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test_CourseCatalog
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production_CourseCatalog
  pool: 5
  username:
  password:
